export const SystemState = {
    BOOTSTRAP: 'BOOTSTRAP',
    LOADING_ASSETS: 'LOADING_ASSETS',
    INITIALIZING_RENDERER: 'INITIALIZING_RENDERER',
    INITIALIZING_AI: 'INITIALIZING_AI', // Specific for MediaPipe
    READY: 'READY',
    ERROR: 'ERROR'
};
